module.exports = {
  ACTION_SET_FLOW_INSTANCE: "ACTION_SET_FLOW_INSTANCE",
  ACTION_SET_TOOL_CONTENT: "ACTION_SET_TOOL_CONTENT",
  ACTION_ADD_TOOL_ELEMENT: "ACTION_ADD_TOOL_ELEMENT",
  ACTION_DELETE_TOOL_ELEMENT: "ACTION_DELETE_TOOL_ELEMENT",
  ACTION_SET_TOOLBOX_HEADER: "ACTION_SET_TOOLBOX_HEADER",
  SCHEMA_TABLE_TOOL_DATABASE: "toolDatabase",
  SCHEMA_TABLE_TOOL_PAGES: "toolPages",
  SCHEMA_TABLE_WORKFLOWS: "workflows",
  SCHEMA_FIELD_ID: "_id",
  SCHEMA_FIELD_VERSION: "version",
  SCHEMA_FIELD_NAME: "name",
  SCHEMA_FIELD_TOOL_PAGE: "toolPage",
  SCHEMA_FIELD_TOOLS_DATA: "toolContent",
  SCHEMA_FIELD_ANCHORS: "toolAnchors",
  SCHEMA_FIELD_VIDEO_TITLE: "videoTitle",
  SCHEMA_FIELD_TOOL_PAGE_VERSION: "toolPageVersion",
  SCHEMA_FIELD_TOOLBOX: "toolbox",
  DB_NAME: "toolsOverviewDb",
  VIEWS: {
    MENU: "MENU",
    EDIT: "EDIT",
    TOOLBOX: "TOOLBOX",
    MAIN: "MAIN",
    TOOLSDATABASE: "TOOLSDATABASE",
    LOADING: "LOADING",
    MENU_INTERNAL: {
      CREATE_WORKFLOW: "MENU_INTERNAL.CREATE_WORKFLOW",
      CREATE_TOOLBOX: "MENU_INTERNAL.CREATE_TOOLBOX",
      REQUEST_SUBMISSION: "MENU_INTERNAL.REQUEST_SUBMISSION"
    },
    ABOUT_INTERNAL: {
      ABOUT: "ABOUT",
      CONTACT: "CONTACT",
      IMPRINT: "IMPRINT"
    }
  },
  CREATE_WORKFLOW_MENU: "CREATE_WORKFLOW_MENU",
  CREATE_TOOLBOX: "CREATE_TOOLBOX",
  TOOLPAGE_INIT_ELEMENT: {"id":"text_0","left":"200px","top":"200px", "height":"", "width":"","content": "", "type":"text", "name": "", "website": "", "description": ""},
  MAIL_OWNER: "webmaster@nightlife-city.com",
  VIDEO_TOOLBOX_EDIT_TUTORIAL: "https://youtu.be/1c-juZp5vQc",
  VIDEO_WORKFLOW_SUBMIT_TUTORIAL: "https://youtu.be/4kYQ89v2atQ",
  VIDEO_REQUEST_TUTORIAL: "https://youtu.be/4kYQ89v2atQ",
  PROXY_URL: "http://cors.io/?"

}
