module.exports = {
  ACTION_SET_FLOW_INSTANCE: "ACTION_SET_FLOW_INSTANCE",
  ACTION_SET_TOOL_CONTENT: "ACTION_SET_TOOL_CONTENT",
  ACTION_ADD_TOOL_ELEMENT: "ACTION_ADD_TOOL_ELEMENT",
  ACTION_DELETE_TOOL_ELEMENT: "ACTION_DELETE_TOOL_ELEMENT",
  SCHEMA_TABLE_TOOL_DATABASE: "toolDatabase",
  SCHEMA_TABLE_TOOL_PAGES: "toolPages",
  SCHEMA_TABLE_WORKFLOWS: "workflows",
  SCHEMA_FIELD_ID: "_id",
  SCHEMA_FIELD_VERSION: "version",
  SCHEMA_FIELD_NAME: "name",
  SCHEMA_FIELD_TOOL_PAGE: "toolPage",
  SCHEMA_FIELD_TOOLS_DATA: "toolContent",
  SCHEMA_FIELD_ANCHORS: "toolAnchors",
  SCHEMA_FIELD_VIDEO_TITLE: "videoTitle",
  SCHEMA_FIELD_TOOL_PAGE_VERSION: "toolPageVersion",
  SCHEMA_FIELD_TOOLBOX: "toolbox",
  DB_NAME: "toolsOverviewDb",
  VIEWS: {
    MENU: "MENU",
    EDIT: "EDIT",
    TOOLBOX: "TOOLBOX",
    MAIN: "MAIN",
    LOADING: "LOADING",
    MENU_INTERNAL: {
      CREATE_WORKFLOW: "MENU_INTERNAL.CREATE_WORKFLOW",
      CREATE_TOOLBOX: "MENU_INTERNAL.CREATE_TOOLBOX",
      REQUEST: "MENU_INTERNAL.REQUEST"
    }
  },
  CREATE_WORKFLOW_MENU: "CREATE_WORKFLOW_MENU",
  CREATE_TOOLBOX: "CREATE_TOOLBOX",
  TOOLPAGE_INIT_ELEMENT: {"id":"text_0","left":"800px","top":"200px", "height":"", "width":"","content": "", "type":"text", "name": "", "website": "", "description": ""}
}
