module.exports = {
  ACTION_SET_FLOW_INSTANCE: "ACTION_SET_FLOW_INSTANCE",
  ACTION_SET_TOOL_CONTENT: "ACTION_SET_TOOL_CONTENT",
  ACTION_ADD_TOOL_ELEMENT: "ACTION_ADD_TOOL_ELEMENT",
  ACTION_DELETE_TOOL_ELEMENT: "ACTION_DELETE_TOOL_ELEMENT",
  SCHEMA_TABLE_TOOL_DATABASE: "toolDatabase",
  SCHEMA_TABLE_TOOL_PAGES: "toolPages",
  SCHEMA_FIELD_ID: "_id",
  SCHEMA_FIELD_VERSION: "version",
  SCHEMA_FIELD_NAME: "name",
  SCHEMA_FIELD_TOOL_PAGE: "toolPage",
  SCHEMA_FIELD_TOOLS_DATA: "toolContent",
  SCHEMA_FIELD_ANCHORS: "toolAnchors",
  DB_NAME: "toolsOverviewDb",
  VIEWS: {
    MENU: "MENU",
    EDIT: "EDIT",
    MAIN: "MAIN"
  }
}
